---
title: "rate"
format: html
---

## Packages

```{r}
library(tidyverse)
library(cmdstanr)
source("functions.R")
source("rate_functions.R")
source("predictions_functions.R")
```

try it for one

```{r}
leagues %>% slice(90) %>% 
  mutate(fname = make_fname(country, league, season, part, prefix = "")) %>% pull(fname) -> my_fname
# my_fname <- "wal_premier-league_2023-2024.rds"
# my_fname <- "nor_eliteserien_2023.rds"
# my_fname <- "swe_allsvenskan_2023.rds"
my_fit <- rate(my_fname)
```

```{r}
typeof(my_fit$fit)
```

```{r}
# my_fit$fit$summary()
rating_table(my_fname) %>% View()
```

this seems to make sense

## do more than one

find the ones that need doing and do them (or some of them)

```{r}
update_rate(leagues) 
```

## predictions for upcoming games based on most recent ratings

not quite there yet

```{r}
leagues %>% mutate(r = row_number()) %>% 
  rowwise() %>% 
  mutate(fname = make_fname(country, league, season, part, prefix = "")) %>% 
  mutate(mtime = file.mtime(str_c("fit/", fname))) %>% 
  mutate(size = file.size(str_c("fit/", fname))) %>% 
  filter(!is.na(mtime)) %>% 
  filter(size > 100) %>% 
  slice_sample(n = 2) %>% 
  pull(fname) %>% 
  map(\(x) league_preds(x))
```
